pts/audio: fix linker error caused by missing libmedia
Fixes the following linker error when doing a make checkbuild:

device/generic/brillo/pts/audio/hal-test/audio_hal_playback_test.cpp:52:
error: undefined reference to
'android::IMediaSource::ReadOptions::ReadOptions()'

(cherry picked from commit bdca875d2c4b55809cbb2dcf9ea5129e246cb59e)

Change-Id: I5246e5ffe231f28e40b26a28790317f9437b2672